// Code generated by oto; DO NOT EDIT.

'use strict';

 
// GreeterService makes nice greetings.
export class GreeterService {
	
	// Greet makes a greeting.
	async greet(greetRequest) {
		const headers = {
			'Accept': 'application/json',
			'Content-Type': 'application/json',
		}
		greetRequest = greetRequest || {}
		const response = await fetch('/oto/GreeterService.Greet', {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(greetRequest)
		})
		return response.json().then(json => {
			if (json.error) {
				throw new Error(json.error)
			}
			return json
		})
	}
	
}
 
export class MathService {
	
		async add(addRequest) {
		const headers = {
			'Accept': 'application/json',
			'Content-Type': 'application/json',
		}
		addRequest = addRequest || {}
		const response = await fetch('/oto/MathService.Add', {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(addRequest)
		})
		return response.json().then(json => {
			if (json.error) {
				throw new Error(json.error)
			}
			return json
		})
	}
	
		async subtract(subtractRequest) {
		const headers = {
			'Accept': 'application/json',
			'Content-Type': 'application/json',
		}
		subtractRequest = subtractRequest || {}
		const response = await fetch('/oto/MathService.Subtract', {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(subtractRequest)
		})
		return response.json().then(json => {
			if (json.error) {
				throw new Error(json.error)
			}
			return json
		})
	}
	
}

